Моки для карточек и отзывов. Шапка и футер выделены в отдельные компо…
htmlacademy-react/197143-six-cities-5 pull request #5
Opened 2020-10-09 09:42 UTC by Julyme3

…ненты

2020-10-09 10:16 UTC, Sasha-belokur requested changes

2020-10-09 10:16 UTC, Sasha-belokur commented on src/components/offer-card/offer-card.jsx
> +      }}
как-то слишком сложно :)
Достаточно просто вызвать функцию с оффером, а внизу в PropTypes описать, что эта функция обязательная и компонент ожидает, что она в любом случае будет

2020-10-09 10:16 UTC, Sasha-belokur commented on src/components/offer-list/offer-list.jsx
> +    }));
Обновлять стейт с помощью функции нужно только в том случае, когда мы хотим знать предыдущее состояние.

т.е. например:
`this.setState((lastCount) => ({
      count: lastCount + 1
    }));`

а здесь мы можем просто передать объект

2020-10-10 17:21 UTC, Julyme3 commented on src/components/offer-card/offer-card.jsx
> +      }}
@Sasha-belokur а как быть если я хочу OfferCard использовать в RoomScreen (где полное описание оффера, ближайшие предложения под картой) но там handleCardHover не должно быть? Не понимаю этот момент)

2020-10-10 17:22 UTC, Julyme3 commented on src/components/offer-list/offer-list.jsx
> +    }));
@Sasha-belokur спасибо, поправлю)

2020-10-12 13:19 UTC, merged